[package]
name = "typsium-atomic"
version = "0.2.0"
repository = "https://github.com/Typsium/typsium-atomic"
license = "MIT"
entrypoint = "lib.typ"
authors = [
    "Typsium Community <https://github.com/Typsium>",
    "Aarav Garg <https://github.com/aargar1>",
    "Ants Aare Alamaa <@Ants-Aare>"
]
description = "Draw Atoms, their electron configurations, shells and orbitals in Typst."
categories = [ "layout", "text", "paper" ]
disciplines = [ "education", "chemistry" ]
keywords = ["chemistry", "chemical", "formula", "electron", "atom", "orbital", "shell", "configuration", "Bohr", "model"]